[package]
name = "mirage"
version = "1.0.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>, Jamil Lambert <jamil.lambert@proton.me>"]
edition = "2018"

[dependencies]
image = "0.21.1"
num-complex = "0.2.1"
